/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"

char **
ls_1_svc(char *str,  struct svc_req *rqstp)
{
	static char * result;

	result = (char *) malloc(20 * sizeof(char));
	sprintf(result, "%s%s", str, str);
	// free(result);
	/*
	 * insert server code here
	 */

	return &result;
}
