/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	// register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, FILENAME_LENGTH))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chunk (XDR *xdrs, chunk *objp)
{
	// register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, FILENAME_LENGTH))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, DATA_LENGTH))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dest_offset))
		 return FALSE;
	return TRUE;
}
