/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


char *
nfs_program_1(char *host, char *str)
{
	CLIENT *clnt;
	char * *result_1;
	// char *ls_1_str;

#ifndef	DEBUG
	clnt = clnt_create (host, NFS_PROGRAM, NFS_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ls_1(str, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s <server_host>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char *result = nfs_program_1 (host, argv[2]);
	printf("%s", result);
exit (0);
}
