/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"

int *
ls_1_svc(int value,  struct svc_req *rqstp)
{
	static int  result;
	result = value * 2;
	/*
	 * insert server code here
	 */

	return &result;
}
