/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


int
nfs_program_1(char *host, int value)
{
	CLIENT *clnt;
	int  *result_1;
	// int ls_1_value;

#ifndef	DEBUG
	clnt = clnt_create (host, NFS_PROGRAM, NFS_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ls_1(value, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s <server_host> <value>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int result = nfs_program_1 (host, atoi(argv[2]));
	printf("%d\n", result);
exit (0);
}
